# Generated by Django 3.2.7 on 2021-09-26 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.TextField(unique=True, verbose_name='name'),
        ),
    ]
