# Generated by Django 3.2.7 on 2021-09-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_remove_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='name'),
        ),
    ]
